# Generated by Django 3.2.9 on 2021-12-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211122_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
