# Generated by Django 3.2.9 on 2021-12-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_movie_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='name',
        ),
    ]
